### ISSUE TITLE
Updating one package updates all available updates

### ISSUE THREAD

**Issue by direc85** [mentaljam/harbour-storeman#106] opened 2019-09-26 07:17 UTC
Hi,

This happened on both of my SFOS devices, XA2 and XA2 Ultra, running 3.1.0 and Storeman 0.1.6.

- Storeman notifies about available updates
- Available updates: YTPlayer (0.6.7 >> 0.6.11) and Advanced Camera (0.3.0 >> 0.4.0)
- Long-press YTPlayer
- Select Update from context menu
- Let the update install

What should happen:
- Long press Advanced Camera
- Select Update from context menu
- Let the update install

What happens:
- Advanced Camera shows old version 0.3.0 but no update available
- Search and open the app page
- The installed and available version is the new 0.4.0
- Close Storeman
- Open Storeman
- Check applications
- Now Advanced Camera shows new version 0.4.0

**Comment by mentaljam** [comment] 2019-10-01 08:59
Close as duplicate of  #96

**Closed by mentaljam** 2019-10-01 08:59 UTC
