### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by objectifnul** [mentaljam/harbour-storeman#124] opened 2020-06-16 15:21 UTC
The search screen has become unreadable after 3.3.0.16 upgrade. The search field and the help tip overlap each other. 
![Capture d'écran_20200616_001](https://user-images.githubusercontent.com/28792006/84794522-a1d30c00-aff6-11ea-9bf8-d68d8d037cb0.png)

**Comment by mentaljam** [comment] 2020-06-17 20:12
Close as duplicate of #117

**Closed by mentaljam** 2020-06-17 20:12 UTC
