### ISSUE TITLE
[Enhancement]Open changelog directly in a browser if only contains a link

### ISSUE THREAD

**Issue by martonmiklos** [mentaljam/harbour-storeman#111] opened 2019-12-12 08:55 UTC
I have seen many applications on openrepos which changelog is not updated at openrepos but the developer simply put a  link to the Github/whatever release page (often with some additional text like "See https://github.com/rinigus/pure-maps/releases"). 

I think if the changelog on openrepos only contains a valid http/https url it should be opened in the browser without going to the changelog page. Once storeman would support this we could propagate this feature to the openrepos submitters to remove the non url part of the Changelog texts. We can even write some regexp to extract urls from the changelog, to do a decision based on the text/url content ratio whether it is useful to open the URL immediately.

@mentaljam  If you like this idea I can came up with a PR.

**Comment by mentaljam** [comment] 2019-12-19 22:08
Thank you for the idea. A PR is welcome :)

**Comment by Olf0** [comment] 2020-05-27 19:04
@martonmiklos (copied from https://openrepos.net/comment/33680#comment-33680):
That does not work [as (you) promised](https://openrepos.net/comment/33156#comment-33156), despite the single link's text now covers all characters of sfos-upgrade's changelog field at OpenRepos except for three. :(

**Comment by martonmiklos** [comment] 2020-05-27 19:47
@Olf0 what version of storeman do you use? I have just tried out with storeman 0.1.8 it and worked..
What happens when you click on the Changelog menu item in the Storeman?
If nothing happens then something is problematic with the URL opening on your system. If you land on the Changelog page of the Storeman then something is terribly wrong (non deterministic) in our code.

**Comment by Olf0** [comment] 2020-05-27 20:11
@martonmiklos, I am using the current Storeman 0.1.8, just like you.
It works fine with e.g. PureMaps: Tap on "Changelog" in Storeman and it directly offers to open it with a browser.
But for sfos-upgrade it displays Storeman's usual changelog page:
![Screenshot_20200527_001](https://user-images.githubusercontent.com/16547876/83066768-d5f58580-a065-11ea-9057-9a321c5286bf.png)
Is this the behaviour you addressed by
> If you land on the Changelog page of the Storeman then something is terribly wrong (non deterministic) in our code.

?

P.S.: In Storeman's changelog sub-page, tapping on a web-link offers to open it in a browser, as (IIRC) Storeman always did.  I suppose that is not the intended behaviour (anymore), right?

**Comment by mentaljam** [comment] 2020-05-28 06:12
I can confirm the strange behaviour. Sometimes a browser opens, sometimes a changelog page.

**Comment by martonmiklos** [comment] 2020-05-28 07:39
Well by pressing it for a while I was able to reproduce the issue. I will add some debug out to see what's part of my regexp condition is lying.

**Comment by mentaljam** [comment] 2020-05-28 07:49
I think regexp is ok. Maybe the changelog property in some conditions become empty.

**Comment by mentaljam** [comment] 2020-05-28 07:51
I also can reproduce it for Pure Maps.

**Comment by martonmiklos** [comment] 2020-05-28 08:20
Maybe we should move the onClicked connecting of the Changelog button to the onOrnRequestFinished to make sure that the app details are loaded when the browser/changelog page decision is made.

**Comment by mentaljam** [comment] 2020-06-17 21:34
I think a have solved the issue. I have an assumption that due to QML caching our regexp is used multiple times on the same string and tries to search the next URL in the changelog ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#Examples)). So I just removed the `g` flag and voila, everything works fine!

**Closed** 2020-06-17 21:40 UTC
Labels: bug
